global:
  scrape_interval: 15s
  evaluation_interval: 15s


scrape_configs:
  - job_name: "archi-service"
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ "host.docker.internal:8083" ]

  - job_name: "archi-admin"
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ "host.docker.internal:8081" ]

  - job_name: "archi-ai"
    metrics_path: '/metrics'
    static_configs:
      - targets: [ "host.docker.internal:8082" ]

  - job_name: "mysql-exporter"
    static_configs:
      - targets: [ "host.docker.internal:9104" ]